In [1]:
from pathlib import Path
import pandas as pd
import pprint
import os
from datetime import datetime
from geopy.distance import geodesic
from geopy.geocoders import Nominatim
import time

In [14]:
csv_citibike = Path("../Resources/202301-citibike-tripdata.csv")
citibike_df1 = pd.read_csv(csv_citibike,low_memory=False)
citibike_df1['started_at'] = pd.to_datetime(citibike_df1['started_at'])
citibike_df1['ended_at'] = pd.to_datetime(citibike_df1['ended_at'])
citibike_df1['start_date'] = citibike_df1['started_at'].dt.date
citibike_df1['start_time'] = citibike_df1['started_at'].dt.time
citibike_df1['ended_date'] = citibike_df1['ended_at'].dt.date
citibike_df1['ended_time'] = citibike_df1['ended_at'].dt.time
citibike_df1

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,ended_date,ended_time
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44,2023-01-26 11:05:17,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,40.777057,-73.978985,member,2023-01-26,10:53:44,2023-01-26,11:05:17
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54,2023-01-04 12:07:09,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,40.693261,-73.968896,casual,2023-01-04,11:51:54,2023-01-04,12:07:09
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48,2023-01-04 17:43:29,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,40.767272,-73.993929,casual,2023-01-04,17:26:48,2023-01-04,17:43:29
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11,2023-01-04 08:42:12,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,40.759291,-73.988597,member,2023-01-04,08:31:11,2023-01-04,08:42:12
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34,2023-01-03 22:30:35,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,40.765909,-73.976342,casual,2023-01-03,22:15:34,2023-01-03,22:30:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1855196,E4317A223A047233,classic_bike,2023-01-02 17:29:12,2023-01-02 18:14:59,Cedar St & Myrtle Ave,4751.01,W 21 St & 6 Ave,6140.05,40.697740,-73.926391,40.741740,-73.994156,member,2023-01-02,17:29:12,2023-01-02,18:14:59
1855197,ABE3E9D3F081A13E,classic_bike,2023-01-03 17:47:28,2023-01-03 17:52:21,E 115 St & Madison Ave,7599.02,Park Ave & E 124 St,7682.01,40.798944,-73.944846,40.804555,-73.939686,member,2023-01-03,17:47:28,2023-01-03,17:52:21
1855198,8F1B225FFE447DD6,classic_bike,2023-01-12 20:18:52,2023-01-12 20:21:31,E 14 St & 1 Ave,5779.10,E 12 St & Ave C,5616.08,40.731402,-73.982845,40.727243,-73.976831,member,2023-01-12,20:18:52,2023-01-12,20:21:31
1855199,A631B3D94A1BBE4F,classic_bike,2023-01-13 00:16:36,2023-01-13 00:26:56,Sullivan Pl & Bedford Ave,3736.04,Kosciuszko St & Nostrand Ave,4519.04,40.664281,-73.957594,40.690725,-73.951335,member,2023-01-13,00:16:36,2023-01-13,00:26:56
1855200,719C2F8C8D500BA2,electric_bike,2023-01-15 15:57:48,2023-01-15 16:05:26,W Broadway & Spring St,5569.06,W 21 St & 6 Ave,6140.05,40.724947,-74.001659,40.741740,-73.994156,member,2023-01-15,15:57:48,2023-01-15,16:05:26

In [15]:
csv_citibike = Path("../Resources/202302-citibike-tripdata.csv")
citibike_df2 = pd.read_csv(csv_citibike,low_memory=False)
citibike_df2['started_at'] = pd.to_datetime(citibike_df2['started_at'])
citibike_df2['ended_at'] = pd.to_datetime(citibike_df2['ended_at'])
citibike_df2['start_date'] = citibike_df2['started_at'].dt.date
citibike_df2['start_time'] = citibike_df2['started_at'].dt.time
citibike_df2['ended_date'] = citibike_df2['ended_at'].dt.date
citibike_df2['ended_time'] = citibike_df2['ended_at'].dt.time
citibike_df2

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,ended_date,ended_time
0,16991A7C313082EB,classic_bike,2023-02-16 18:20:42,2023-02-16 18:38:06,Kosciuszko St & Nostrand Ave,4519.04,Eastern Pkwy & Troy Ave,3862.07,40.690698,-73.951423,40.669290,-73.936790,casual,2023-02-16,18:20:42,2023-02-16,18:38:06
1,856FFB566BEEB824,classic_bike,2023-02-09 17:29:36,2023-02-09 17:33:07,Riverside Dr & W 138 St,7942.21,St. Nicholas Terrace & Convent Ave,7937.15,40.823134,-73.955860,40.821294,-73.947868,member,2023-02-09,17:29:36,2023-02-09,17:33:07
2,B1FE28D50B493430,classic_bike,2023-02-16 15:33:51,2023-02-16 15:35:01,Clinton St & Tillary St,4748.07,Clark St & Henry St,4789.03,40.696233,-73.991421,40.697601,-73.993446,member,2023-02-16,15:33:51,2023-02-16,15:35:01
3,870EA3D724EA6162,classic_bike,2023-02-23 17:11:39,2023-02-23 17:12:56,Clinton St & Tillary St,4748.07,Clark St & Henry St,4789.03,40.696233,-73.991421,40.697601,-73.993446,member,2023-02-23,17:11:39,2023-02-23,17:12:56
4,7DE8FA9EAAE8C4ED,electric_bike,2023-02-18 19:29:17,2023-02-18 19:50:52,Audubon Ave & W 192 St,8469.05,St. Nicholas Terrace & Convent Ave,7937.15,40.855890,-73.927082,40.821294,-73.947868,member,2023-02-18,19:29:17,2023-02-18,19:50:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1752143,389430A56EA04541,electric_bike,2023-02-21 12:40:49,2023-02-21 12:43:41,W 22 St & 10 Ave,6306.06,W 22 St & 8 Ave,6224.03,40.746920,-74.004519,40.744751,-73.999154,member,2023-02-21,12:40:49,2023-02-21,12:43:41
1752144,653158DC3395255E,classic_bike,2023-02-14 16:20:36,2023-02-14 17:03:37,W 47 St & 6 Ave,6667.04,W 51 St & 6 Ave,6740.10,40.758397,-73.982550,40.760660,-73.980420,member,2023-02-14,16:20:36,2023-02-14,17:03:37
1752145,C3707AC98071DDAD,classic_bike,2023-02-11 16:52:16,2023-02-11 17:12:15,W 22 St & 10 Ave,6306.06,W 22 St & 8 Ave,6224.03,40.746920,-74.004519,40.744751,-73.999154,member,2023-02-11,16:52:16,2023-02-11,17:12:15
1752146,F3A6D114409FA6A1,classic_bike,2023-02-22 19:25:20,2023-02-22 19:28:54,W 22 St & 10 Ave,6306.06,W 22 St & 8 Ave,6224.03,40.746920,-74.004519,40.744751,-73.999154,member,2023-02-22,19:25:20,2023-02-22,19:28:54
1752147,0F4573E00346E489,classic_bike,2023-02-03 18:54:53,2023-02-03 18:57:54,W 47 St & 6 Ave,6667.04,W 51 St & 6 Ave,6740.10,40.758397,-73.982550,40.760660,-73.980420,member,2023-02-03,18:54:53,2023-02-03,18:57:54

In [16]:
csv_citibike = Path("../Resources/202303-citibike-tripdata.csv")
citibike_df3 = pd.read_csv(csv_citibike,low_memory=False)
citibike_df3['started_at'] = pd.to_datetime(citibike_df3['started_at'])
citibike_df3['ended_at'] = pd.to_datetime(citibike_df3['ended_at'])
citibike_df3['start_date'] = citibike_df3['started_at'].dt.date
citibike_df3['start_time'] = citibike_df3['started_at'].dt.time
citibike_df3['ended_date'] = citibike_df3['ended_at'].dt.date
citibike_df3['ended_time'] = citibike_df3['ended_at'].dt.time
citibike_df3

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,ended_date,ended_time
0,EAB9FFEAB7BDBAF2,classic_bike,2023-03-15 18:11:59,2023-03-15 18:18:38,6 Ave & W 33 St,6364.07,9 Ave & W 22 St,6266.06,40.748423,-73.988208,40.745497,-74.001971,member,2023-03-15,18:11:59,2023-03-15,18:18:38
1,B57211E2408E604F,classic_bike,2023-03-18 21:05:59,2023-03-18 21:10:51,6 Ave & W 33 St,6364.07,W 35 St & 9 Ave,6569.09,40.749134,-73.988536,40.754145,-73.996089,member,2023-03-18,21:05:59,2023-03-18,21:10:51
2,9411DD44FB7406A9,classic_bike,2023-03-16 10:16:15,2023-03-16 10:24:27,6 Ave & W 33 St,6364.07,W 35 St & 9 Ave,6569.09,40.749013,-73.988484,40.754145,-73.996089,member,2023-03-16,10:16:15,2023-03-16,10:24:27
3,DC2D4F90D746F435,classic_bike,2023-03-01 06:55:20,2023-03-01 07:05:44,E 5 St & Ave A,5626.06,8 Ave & W 31 St,6450.05,40.724775,-73.983742,40.750585,-73.994685,member,2023-03-01,06:55:20,2023-03-01,07:05:44
4,63874304EFBD61EE,classic_bike,2023-03-02 23:21:02,2023-03-02 23:42:19,3 Ave & Schermerhorn St,4437.01,Greenpoint Ave & Manhattan Ave,5785.05,40.686803,-73.979754,40.730260,-73.953940,member,2023-03-02,23:21:02,2023-03-02,23:42:19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2194209,57870BEBA3FF73E4,classic_bike,2023-03-31 05:46:55,2023-03-31 05:49:53,11 Ave & W 27 St,6425.04,W 34 St & 11 Ave,6578.01,40.751396,-74.005226,40.755942,-74.002116,member,2023-03-31,05:46:55,2023-03-31,05:49:53
2194210,4E31529528517CC8,electric_bike,2023-03-16 02:18:25,2023-03-16 02:22:53,11 Ave & W 27 St,6425.04,W 37 St & 10 Ave,6611.02,40.751396,-74.005226,40.756604,-73.997901,member,2023-03-16,02:18:25,2023-03-16,02:22:53
2194211,CBE65CCA422B3768,classic_bike,2023-03-17 08:38:51,2023-03-17 08:42:12,11 Ave & W 27 St,6425.04,W 37 St & 10 Ave,6611.02,40.751197,-74.005479,40.756604,-73.997901,member,2023-03-17,08:38:51,2023-03-17,08:42:12
2194212,C6F86C00DD3ABFB0,classic_bike,2023-03-15 19:19:26,2023-03-15 19:32:40,Putnam Ave & Throop Ave,4392.04,Melrose St & Broadway,4801.04,40.685153,-73.941110,40.697481,-73.935877,member,2023-03-15,19:19:26,2023-03-15,19:32:40
2194213,7C2E424FD54ACAD5,classic_bike,2023-03-29 09:13:23,2023-03-29 09:19:46,11 Ave & W 27 St,6425.04,W 37 St & 10 Ave,6611.02,40.751328,-74.005502,40.756604,-73.997901,member,2023-03-29,09:13:23,2023-03-29,09:19:46

In [17]:
csv_citibike = Path("../Resources/202307-citibike-tripdata.csv")
citibike_df7 = pd.read_csv(csv_citibike,low_memory=False)
citibike_df7['started_at'] = pd.to_datetime(citibike_df7['started_at'])
citibike_df7['ended_at'] = pd.to_datetime(citibike_df7['ended_at'])
citibike_df7['start_date'] = citibike_df7['started_at'].dt.date
citibike_df7['start_time'] = citibike_df7['started_at'].dt.time
citibike_df7['ended_date'] = citibike_df7['ended_at'].dt.date
citibike_df7['ended_time'] = citibike_df7['ended_at'].dt.time
citibike_df7

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,ended_date,ended_time
0,BC78328130CD8A16,classic_bike,2023-07-16 20:42:57,2023-07-16 20:45:13,St. Nicholas Ave & W 126 St,7756.10,Adam Clayton Powell Blvd & W 126 St,7738.04,40.811432,-73.951878,40.809495,-73.947765,member,2023-07-16,20:42:57,2023-07-16,20:45:13
1,71A4DFA231ADAEA2,classic_bike,2023-07-29 12:22:21,2023-07-29 12:26:54,Adam Clayton Powell Blvd & W 118 St,7670.09,Adam Clayton Powell Blvd & W 126 St,7738.04,40.804372,-73.951475,40.809495,-73.947765,member,2023-07-29,12:22:21,2023-07-29,12:26:54
2,B64451D0D9F52134,classic_bike,2023-07-30 18:30:18,2023-07-30 18:35:42,St. Nicholas Ave & W 126 St,7756.10,Lenox Ave & W 130 St,7753.13,40.811378,-73.951827,40.810792,-73.943068,member,2023-07-30,18:30:18,2023-07-30,18:35:42
3,EEECB3E0E05EB0DB,classic_bike,2023-07-04 19:59:20,2023-07-04 20:02:03,St. Nicholas Ave & W 126 St,7756.10,Adam Clayton Powell Blvd & W 126 St,7738.04,40.811432,-73.951878,40.809495,-73.947765,member,2023-07-04,19:59:20,2023-07-04,20:02:03
4,76B706DF4FC180DC,classic_bike,2023-07-03 19:33:36,2023-07-03 19:43:59,St. Nicholas Ave & W 126 St,7756.10,Pleasant Ave & E 116 St,7450.05,40.811543,-73.951813,40.794988,-73.933335,member,2023-07-03,19:33:36,2023-07-03,19:43:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3776251,8EB48FBE46A673DF,classic_bike,2023-07-28 19:11:45,2023-07-28 19:38:24,S 4 St & Rodney St,5156.05,Irving Ave & Halsey St,4695.04,40.709340,-73.956080,40.694670,-73.906630,member,2023-07-28,19:11:45,2023-07-28,19:38:24
3776252,8B66692B4C236E00,classic_bike,2023-07-11 20:09:42,2023-07-11 20:38:01,Madison Ave & E 120 St,7667.04,Intervale Ave & Westchester Ave,7948.10,40.803026,-73.942863,40.821967,-73.896752,member,2023-07-11,20:09:42,2023-07-11,20:38:01
3776253,86E2D896051F1420,classic_bike,2023-07-25 21:05:48,2023-07-25 21:10:15,Windsor Pl & Howard Pl,3579.04,14 St & 5 Ave,3771.06,40.659647,-73.980421,40.666287,-73.988951,member,2023-07-25,21:05:48,2023-07-25,21:10:15
3776254,556B12591EC0C385,classic_bike,2023-07-15 13:15:14,2023-07-15 13:25:55,DeKalb Ave & Vanderbilt Ave,4461.04,Broadway & Kent Ave,5134.09,40.689412,-73.968847,40.710888,-73.968329,member,2023-07-15,13:15:14,2023-07-15,13:25:55
3776255,1FE35D1565CF12ED,electric_bike,2023-07-05 09:19:00,2023-07-05 09:21:34,E 117 St & 1 Ave,7579.11,E 116 St & 2 Ave,7563.06,40.796568,-73.934595,40.796879,-73.937261,member,2023-07-05,09:19:00,2023-07-05,09:21:34

In [18]:
csv_citibike = Path("../Resources/202308-citibike-tripdata.csv")
citibike_df8 = pd.read_csv(csv_citibike,low_memory=False)
citibike_df8['started_at'] = pd.to_datetime(citibike_df8['started_at'])
citibike_df8['ended_at'] = pd.to_datetime(citibike_df8['ended_at'])
citibike_df8['start_date'] = citibike_df8['started_at'].dt.date
citibike_df8['start_time'] = citibike_df8['started_at'].dt.time
citibike_df8['ended_date'] = citibike_df8['ended_at'].dt.date
citibike_df8['ended_time'] = citibike_df8['ended_at'].dt.time
citibike_df8

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,ended_date,ended_time
0,C5E94016E7939757,classic_bike,2023-08-29 21:15:27,2023-08-29 21:51:04,Lexington Ave & E 36 St,6313.10,Amsterdam Ave & W 125 St,7800.03,40.747574,-73.978801,40.813358,-73.956461,member,2023-08-29,21:15:27,2023-08-29,21:51:04
1,E88D94798ABBBD7C,classic_bike,2023-08-06 19:03:35,2023-08-06 19:04:56,Rockaway Ave & Bainbridge St,4285.09,MacDougal St & Rockaway Ave,4212.01,40.683236,-73.911943,40.680180,-73.911360,member,2023-08-06,19:03:35,2023-08-06,19:04:56
2,341D3CE4743A92EC,classic_bike,2023-08-02 20:34:04,2023-08-02 20:40:19,W 13 St & 5 Ave,5947.04,E 10 St & 2 Ave,5746.02,40.735445,-73.994310,40.729708,-73.986598,member,2023-08-02,20:34:04,2023-08-02,20:40:19
3,21C763DECA96FD02,classic_bike,2023-08-14 13:47:23,2023-08-14 14:17:36,Central Park North & Adam Clayton Powell Blvd,7617.07,5 Ave & E 29 St,6248.06,40.799484,-73.955613,40.745168,-73.986831,member,2023-08-14,13:47:23,2023-08-14,14:17:36
4,A8533C28598A6AB8,classic_bike,2023-08-03 13:05:09,2023-08-03 13:52:27,W 13 St & 5 Ave,5947.04,Amsterdam Ave & W 125 St,7800.03,40.735445,-73.994310,40.813358,-73.956461,member,2023-08-03,13:05:09,2023-08-03,13:52:27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4093164,1DF107B2D3236068,classic_bike,2023-08-01 17:08:26,2023-08-01 17:17:22,W 17 St & 8 Ave,6148.02,Gramercy Park N & Gramercy Park E,6013.12,40.741776,-74.001497,40.737950,-73.985090,member,2023-08-01,17:08:26,2023-08-01,17:17:22
4093165,168B289864D8DE47,classic_bike,2023-08-27 17:06:25,2023-08-27 17:23:47,W 17 St & 8 Ave,6148.02,W 47 St & 10 Ave,6824.07,40.741776,-74.001497,40.762699,-73.993012,member,2023-08-27,17:06:25,2023-08-27,17:23:47
4093166,18FC63FE8411C4B1,classic_bike,2023-08-24 08:22:50,2023-08-24 08:32:43,Bergen St & Vanderbilt Ave,4157.10,Kingston Ave & Herkimer St,4205.06,40.679461,-73.967905,40.678907,-73.941428,member,2023-08-24,08:22:50,2023-08-24,08:32:43
4093167,8806D0CDD899C339,classic_bike,2023-08-06 13:33:22,2023-08-06 13:38:43,Adam Clayton Powell Blvd & W 123 St,7704.04,Lenox Ave & W 133 St,7790.04,40.807832,-73.949373,40.812960,-73.941878,member,2023-08-06,13:33:22,2023-08-06,13:38:43
4093168,FEDA43F66995347C,classic_bike,2023-08-29 17:02:02,2023-08-29 17:04:51,E 7 St & Avenue A,5626.07,E 13 St & Avenue A,5779.09,40.726218,-73.983799,40.729667,-73.980680,member,2023-08-29,17:02:02,2023-08-29,17:04:51

In [19]:
csv_citibike = Path("../Resources/202309-citibike-tripdata.csv")
citibike_df9 = pd.read_csv(csv_citibike,low_memory=False)
citibike_df9['started_at'] = pd.to_datetime(citibike_df9['started_at'])
citibike_df9['ended_at'] = pd.to_datetime(citibike_df9['ended_at'])
citibike_df9['start_date'] = citibike_df9['started_at'].dt.date
citibike_df9['start_time'] = citibike_df9['started_at'].dt.time
citibike_df9['ended_date'] = citibike_df9['ended_at'].dt.date
citibike_df9['ended_time'] = citibike_df9['ended_at'].dt.time
citibike_df9

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,ended_date,ended_time
0,B0A0F1DEFA4B72FC,electric_bike,2023-09-03 10:20:41,2023-09-03 10:24:16,E 1 St & Bowery,5636.13,E 10 St & 2 Ave,5746.02,40.724861,-73.992131,40.729708,-73.986598,member,2023-09-03,10:20:41,2023-09-03,10:24:16
1,2B26AB15647BF4EE,classic_bike,2023-09-27 15:44:23,2023-09-27 15:53:25,Pearl St & Hanover Square,4993.02,Allen St & Rivington St,5414.06,40.704650,-74.009133,40.720196,-73.989978,member,2023-09-27,15:44:23,2023-09-27,15:53:25
2,9D2B5971CA4E513F,classic_bike,2023-09-19 13:40:48,2023-09-19 13:48:11,E 1 St & Bowery,5636.13,E 10 St & 2 Ave,5746.02,40.724753,-73.992116,40.729708,-73.986598,member,2023-09-19,13:40:48,2023-09-19,13:48:11
3,17E6760596DC3ABE,classic_bike,2023-09-30 16:27:50,2023-09-30 16:56:35,Central Ave & Himrod St,4713.01,Mott St & Prince St,5561.04,40.696706,-73.922935,40.723180,-73.994800,member,2023-09-30,16:27:50,2023-09-30,16:56:35
4,97EFF376A7E2DC70,classic_bike,2023-09-21 16:59:53,2023-09-21 17:07:36,St Marks Pl & 2 Ave,5669.10,Mott St & Prince St,5561.04,40.728419,-73.987140,40.723180,-73.994800,member,2023-09-21,16:59:53,2023-09-21,17:07:36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3575157,472EFFA78D0FBCF2,classic_bike,2023-09-28 18:46:55,2023-09-28 18:59:28,Rogers Ave & Sterling St,3696.05,West Drive & Prospect Park West,3651.04,40.663062,-73.953875,40.661063,-73.979453,member,2023-09-28,18:46:55,2023-09-28,18:59:28
3575158,E986DA2AAB275937,classic_bike,2023-09-12 08:13:58,2023-09-12 08:24:03,Prospect Pl & Underhill Ave,4116.08,Flatbush Ave & Lincoln Rd,3593.1,40.676969,-73.965790,40.661310,-73.960910,member,2023-09-12,08:13:58,2023-09-12,08:24:03
3575159,550CD10C7A00375E,classic_bike,2023-09-11 16:48:06,2023-09-11 17:04:33,E 56 St & Madison Ave,6732.01,E 22 St & 2 Ave,5971.09,40.761573,-73.972628,40.737169,-73.981225,member,2023-09-11,16:48:06,2023-09-11,17:04:33
3575160,D4513B0A34BFD970,classic_bike,2023-09-07 07:42:11,2023-09-07 07:48:58,E 77 St & 3 Ave,7092.06,E 48 St & 3 Ave,6541.03,40.773280,-73.958971,40.754601,-73.971879,member,2023-09-07,07:42:11,2023-09-07,07:48:58
3575161,12A14A1308892249,classic_bike,2023-09-22 13:04:02,2023-09-22 13:12:25,Broadway & W 58 St,6948.10,6 Ave & W 45 St,6593.15,40.766953,-73.981693,40.756951,-73.982631,member,2023-09-22,13:04:02,2023-09-22,13:12:25

In [20]:
df1_subset = citibike_df1.head(len(citibike_df1)//12)
df2_subset = citibike_df2.head(len(citibike_df2)//12)
df3_subset = citibike_df3.head(len(citibike_df3)//12)
df7_subset = citibike_df7.head(len(citibike_df7)//24)
df8_subset = citibike_df8.head(len(citibike_df8)//24)
df9_subset = citibike_df9.head(len(citibike_df9)//24)

In [21]:
result_df = pd.concat([df1_subset, df2_subset, df3_subset,df7_subset,df8_subset,df9_subset], axis=0)
result_df.reset_index(drop=True, inplace=True)
result_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,ended_date,ended_time
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44,2023-01-26 11:05:17,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,40.777057,-73.978985,member,2023-01-26,10:53:44,2023-01-26,11:05:17
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54,2023-01-04 12:07:09,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,40.693261,-73.968896,casual,2023-01-04,11:51:54,2023-01-04,12:07:09
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48,2023-01-04 17:43:29,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,40.767272,-73.993929,casual,2023-01-04,17:26:48,2023-01-04,17:43:29
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11,2023-01-04 08:42:12,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,40.759291,-73.988597,member,2023-01-04,08:31:11,2023-01-04,08:42:12
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34,2023-01-03 22:30:35,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,40.765909,-73.976342,casual,2023-01-03,22:15:34,2023-01-03,22:30:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960315,E8B52ECF7147CF61,classic_bike,2023-09-21 20:37:33,2023-09-21 20:54:04,W 20 St & 8 Ave,6224.05,Broadway & W 38 St,6560.15,40.743453,-74.000040,40.752973,-73.987349,casual,2023-09-21,20:37:33,2023-09-21,20:54:04
960316,404BBFA3EB818A78,classic_bike,2023-09-17 16:49:49,2023-09-17 16:52:43,6 Ave & 9 St,3803.09,14 St & 7 Ave,3731.11,40.668104,-73.983811,40.663779,-73.983968,member,2023-09-17,16:49:49,2023-09-17,16:52:43
960317,06A2BC2E44C02771,classic_bike,2023-09-28 21:18:38,2023-09-28 21:29:05,Bleecker St & Crosby St,5679.08,Clinton St & Grand St,5303.06,40.726156,-73.995102,40.715595,-73.987030,member,2023-09-28,21:18:38,2023-09-28,21:29:05
960318,514C078303C35A61,classic_bike,2023-09-12 15:34:33,2023-09-12 15:43:53,Centre St & Chambers St,5207.01,Clinton St & Grand St,5303.06,40.712733,-74.004607,40.715595,-73.987030,member,2023-09-12,15:34:33,2023-09-12,15:43:53
960319,AC886DEAE344AE86,classic_bike,2023-09-25 12:26:19,2023-09-25 12:31:25,Knickerbocker Ave & Hancock St,4663.02,Madison St & Woodward Ave,4954.07,40.693936,-73.909734,40.704080,-73.904080,member,2023-09-25,12:26:19,2023-09-25,12:31:25

In [2]:
# result_df.to_csv("../Resources/citibike-tripdata-merged.csv", index=False)
csv_citibike = Path("../Resources/citibike-tripdata-merged.csv")
result_df = pd.read_csv(csv_citibike,low_memory=False)
result_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,ended_date,ended_time
0,4A86C1475DCCADA0,classic_bike,2023-01-26 10:53:44,2023-01-26 11:05:17,E 53 St & Madison Ave,6659.03,Columbus Ave & W 72 St,7175.05,40.759724,-73.973664,40.777057,-73.978985,member,2023-01-26,10:53:44,2023-01-26,11:05:17
1,AE02E1FF7E264874,classic_bike,2023-01-04 11:51:54,2023-01-04 12:07:09,Halsey St & Ralph Ave,4334.02,Clinton Ave & Myrtle Ave,4651.02,40.684970,-73.922755,40.693261,-73.968896,casual,2023-01-04,11:51:54,2023-01-04,12:07:09
2,D3F9A2A71AD244C6,classic_bike,2023-01-04 17:26:48,2023-01-04 17:43:29,Bank St & Hudson St,5922.08,W 52 St & 11 Ave,6926.01,40.736566,-74.006092,40.767272,-73.993929,casual,2023-01-04,17:26:48,2023-01-04,17:43:29
3,3D48C6F33AFEF329,classic_bike,2023-01-04 08:31:11,2023-01-04 08:42:12,E 53 St & Madison Ave,6659.03,W 45 St & 8 Ave,6676.02,40.759711,-73.974023,40.759291,-73.988597,member,2023-01-04,08:31:11,2023-01-04,08:42:12
4,4865926C3D97BA01,electric_bike,2023-01-03 22:15:34,2023-01-03 22:30:35,Frederick Douglass Blvd & W 112 St,7631.23,Central Park S & 6 Ave,6876.04,40.801694,-73.957145,40.765909,-73.976342,casual,2023-01-03,22:15:34,2023-01-03,22:30:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960315,E8B52ECF7147CF61,classic_bike,2023-09-21 20:37:33,2023-09-21 20:54:04,W 20 St & 8 Ave,6224.05,Broadway & W 38 St,6560.15,40.743453,-74.000040,40.752973,-73.987349,casual,2023-09-21,20:37:33,2023-09-21,20:54:04
960316,404BBFA3EB818A78,classic_bike,2023-09-17 16:49:49,2023-09-17 16:52:43,6 Ave & 9 St,3803.09,14 St & 7 Ave,3731.11,40.668104,-73.983811,40.663779,-73.983968,member,2023-09-17,16:49:49,2023-09-17,16:52:43
960317,06A2BC2E44C02771,classic_bike,2023-09-28 21:18:38,2023-09-28 21:29:05,Bleecker St & Crosby St,5679.08,Clinton St & Grand St,5303.06,40.726156,-73.995102,40.715595,-73.987030,member,2023-09-28,21:18:38,2023-09-28,21:29:05
960318,514C078303C35A61,classic_bike,2023-09-12 15:34:33,2023-09-12 15:43:53,Centre St & Chambers St,5207.01,Clinton St & Grand St,5303.06,40.712733,-74.004607,40.715595,-73.987030,member,2023-09-12,15:34:33,2023-09-12,15:43:53
960319,AC886DEAE344AE86,classic_bike,2023-09-25 12:26:19,2023-09-25 12:31:25,Knickerbocker Ave & Hancock St,4663.02,Madison St & Woodward Ave,4954.07,40.693936,-73.909734,40.704080,-73.904080,member,2023-09-25,12:26:19,2023-09-25,12:31:25

In [3]:
# How many trips have been recorded in total during the chosen period?
total_trips = len(result_df['start_date'])
total_trips

960320

In [4]:
# By what percentage has total ridership grown?
# Convert 'start_date' column to datetime format
result_df['start_date'] = pd.to_datetime(result_df['start_date'])

# Calculate total ridership for each period
total_ridership_jan = len(result_df[(result_df['start_date'] >= '2023-01-01') & (result_df['start_date'] < '2023-02-01')])
total_ridership_feb = len(result_df[(result_df['start_date'] >= '2023-02-01') & (result_df['start_date'] < '2023-03-01')])
total_ridership_march = len(result_df[(result_df['start_date'] >= '2023-03-01') & (result_df['start_date'] < '2023-04-01')])
total_ridership_jul = len(result_df[(result_df['start_date'] >= '2023-07-01') & (result_df['start_date'] < '2023-08-01')])
total_ridership_aug = len(result_df[(result_df['start_date'] >= '2023-08-01') & (result_df['start_date'] < '2023-09-01')])
total_ridership_sept = len(result_df[(result_df['start_date'] >= '2023-09-01') & (result_df['start_date'] < '2023-10-01')])

# Find the difference
ridership_growth1 = ((total_ridership_feb - total_ridership_jan) / total_ridership_jan) * 100
ridership_growth2 = ((total_ridership_march - total_ridership_feb) / total_ridership_feb) * 100
ridership_growth3 = ((total_ridership_aug - total_ridership_jul) / total_ridership_jul) * 100
ridership_growth4 = ((total_ridership_sept - total_ridership_aug) / total_ridership_aug) * 100


print(f'Percentage growth from January23 to February23: {ridership_growth1:.2f}%')
print(f'Percentage growth from February23 to March23: {ridership_growth2:.2f}%')
print(f'Percentage growth from Aug23 to Jul23: {ridership_growth3:.2f}%')
print(f'Percentage growth from Sept23 to Aug23: {ridership_growth4:.2f}%')

Percentage growth from January23 to February23: -5.55%
Percentage growth from February23 to March23: 25.23%
Percentage growth from Aug23 to Jul23: 8.39%
Percentage growth from Sept23 to Aug23: -12.66%

In [25]:
# Create a DataFrame for each customer type
short_term_customers = result_df[result_df['member_casual'] == 'casual']
annual_subscribers = result_df[result_df['member_casual'] == 'member']
# Calculate the total number of short-term customers and annual subscribers for each time period
total_short_term_customers = short_term_customers.groupby(result_df['start_date'].dt.to_period('M')).size()
total_annual_subscribers = annual_subscribers.groupby(result_df['start_date'].dt.to_period('M')).size()
# Calculate the proportions
proportion_short_term_customers = total_short_term_customers / (total_short_term_customers + total_annual_subscribers)
proportion_annual_subscribers = total_annual_subscribers / (total_short_term_customers + total_annual_subscribers)

# Combine the results into a new DataFrame for easier analysis or visualization
proportions_df = pd.DataFrame({
    'Month': proportion_short_term_customers.index,
    'Proportion Short-term Customers': proportion_short_term_customers.values,
    'Proportion Annual Subscribers': proportion_annual_subscribers.values
})

# Print or plot the results
print(proportions_df)

     Month  Proportion Short-term Customers  Proportion Annual Subscribers
0  2023-01                         0.129612                       0.870388
1  2023-02                         0.122641                       0.877359
2  2023-03                         0.126748                       0.873252
3  2023-07                         0.264497                       0.735503
4  2023-08                         0.297195                       0.702805
5  2023-09                         0.249085                       0.750915

In [26]:
#What are the peak hours when bikes are used during the summer months   
# Assuming 'started_at' is the column containing the ride start timestamps
result_df['started_at'] = pd.to_datetime(result_df['started_at'])

# Extract the hour from the 'started_at' column
result_df['hour'] = result_df['started_at'].dt.hour

# Filter data for summer months
summer_data = result_df[(result_df['started_at'].dt.month >= 7) & (result_df['started_at'].dt.month <= 9)]

# Group by hour and calculate the count for each hour
hourly_counts_summer = summer_data.groupby('hour').size()

# Identify the peak hours
summer_peak_hours = hourly_counts_summer[hourly_counts_summer == hourly_counts_summer.max()].index.tolist()

print(f"Peak hours during the summer months: {', '.join(map(str, summer_peak_hours))}")

Peak hours during the summer months: 17

In [27]:
# What are the peak hours when bikes are used during the Winter  months
# Assuming 'started_at' is the column containing the ride start timestamps
result_df['started_at'] = pd.to_datetime(result_df['started_at'])

# Filter data for summer months
winter_data = result_df[(result_df['started_at'].dt.month >= 1) & (result_df['started_at'].dt.month < 4)]

# Extract the hour from the 'started_at' column
winter_data['hour'] = winter_data['started_at'].dt.hour

# Group by hour and calculate the count for each hour
hourly_counts_winter = winter_data.groupby('hour').size()

# Identify the peak hours
winter_peak_hours = hourly_counts_winter[hourly_counts_winter == hourly_counts_winter.max()].index.tolist()

print(f"Peak hours during the winter months: {', '.join(map(str, winter_peak_hours))}")

Peak hours during the winter months: 17

C:\Users\mh30f\AppData\Local\Temp\ipykernel_7696\767617852.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  winter_data['hour'] = winter_data['started_at'].dt.hour

In [5]:
# what are the top 10 stations in the city for starting a journey? Based on data, why do you hypothesise these are the top locations?
# Assuming 'start_station_name' is the column containing the station names
top_starting_stations = result_df['start_station_name'].value_counts().head(10)

print("Top 10 stations for starting a journey:")
print(top_starting_stations)

Top 10 stations for starting a journey:
8 Ave & W 16 St             7250
Broadway & E 21 St          5458
Central Park S & 6 Ave      4576
W 4 St & 7 Ave S            4455
1 Ave & E 16 St             4305
Lafayette St & Jersey St    4094
West St & Chambers St       4023
Ave A & E 14 St             4022
Allen St & Stanton St       3824
6 Ave & W 33 St             3764
Name: start_station_name, dtype: int64

In [29]:
# what are the top 10 stations in the city for starting a journey? Based on data, why do you hypothesise these are the top locations?
# Assuming 'start_station_name' is the column containing the station names
bottom_starting_stations = result_df['start_station_name'].sort_values(ascending=True).value_counts().tail(30)

print("bottom 10 stations for starting a journey:")
print(bottom_starting_stations)

bottom 10 stations for starting a journey:
Snyder Ave & Schenectady Ave               3
Benham St & Roosevelt Ave                  3
Judge St & Britton Ave                     2
31 Rd & 21 St                              2
25 Ave & 96 St                             2
111 St & Roosevelt Ave                     2
94 St & 57 Ave                             2
Clarkson Ave & Troy Ave                    2
Butler St & 27 Ave                         2
56 Ave & Junction Blvd                     2
Queens Blvd & Broadway                     2
34 Ave & 108 St                            2
31 Ave & 103 St                            1
Hoboken Terminal - River St & Hudson Pl    1
24 Ave & 92 St                             1
2 St & Park Ave                            1
98 St & 41 Ave                             1
Jersey & 6th St                            1
Corona Ave & 102 St                        1
Mama Johnson Field - 4 St & Jackson St     1
Crown St & Troy Ave                        1
Lab - NYC                                  1
53 Ave & 94 St                             1
9 St HBLR - Jackson St & 8 St              1
Van Vorst Park                             1
Morgan Loading Docks                       1
Queens Blvd & 56 Ave                       1
46 Ave & Junction Blvd                     1
47 Ave & 104 St                            1
97 St & 23 Ave                             1
Name: start_station_name, dtype: int64

In [6]:
# what are the top 10 stations in the city for ending a journey? Based on data, why?
# Assuming 'start_station_name' is the column containing the station names
top_ending_stations = result_df['end_station_name'].value_counts().head(10)

print("Top 10 stations for ending a journey:")
print(top_ending_stations)

Top 10 stations for ending a journey:
W 21 St & 6 Ave                  8685
W 31 St & 7 Ave                  5700
W 20 St & 10 Ave                 5634
8 Ave & W 33 St                  4617
North Moore St & Greenwich St    4300
W 25 St & 6 Ave                  4082
E 16 St & 5 Ave                  3705
6 Ave & W 34 St                  3522
Norfolk St & Broome St           3494
11 Ave & W 41 St                 3412
Name: end_station_name, dtype: int64

In [31]:
# what are the bottom 10 stations in the city for ending a journey? Based on data, why?
# Assuming 'end_station_name' is the column containing the station names
bottom_ending_stations = result_df['end_station_name'].value_counts().tail(24)

print("Bottom 10 stations for ending a journey:")
print(bottom_ending_stations)

Bottom 10 stations for ending a journey:
Madison St & 10 St                          1
JC Medical Center                           1
Lafayette Park                              1
Corona Ave & 102 St                         1
Columbus Drive                              1
Grand St                                    1
6 St & Grand St                             1
Van Vorst Park                              1
Hoboken Terminal - Hudson St & Hudson Pl    1
Marshall St & 2 St                          1
Adams St & 11 St                            1
Exchange Pl                                 1
Lab - NYC                                   1
Clinton St & 7 St                           1
Warren St                                   1
4 St & Grand St                             1
Glenwood Ave                                1
Hilltop                                     1
11 St & Washington St                       1
Liberty Light Rail                          1
98 St & 41 Ave                              1
Dwight St & Dikeman St                      1
Case St & 94 St                             1
114 St & 39 Ave                             1
Name: end_station_name, dtype: int64

In [32]:
# How does the average trip duration change by the type of user? (This may be under "User Type" or "member_casual" depending on the period the data is from).
# Convert 'started_at' and 'ended_at' columns to datetime
result_df['started_at'] = pd.to_datetime(result_df['started_at'])
result_df['ended_at'] = pd.to_datetime(result_df['ended_at'])

# Calculate the trip duration in seconds
result_df['trip_duration'] = (result_df['ended_at'] - result_df['started_at']).dt.total_seconds()

# Assuming 'member_casual' is the column name, you may need to replace it with the actual column name
average_duration_by_user = result_df.groupby('member_casual')['trip_duration'].mean()

print("Average trip duration by user type:")
print(average_duration_by_user)

Average trip duration by user type:
member_casual
casual    1642.965743
member     782.833075
Name: trip_duration, dtype: float64

In [33]:
# What is the average distance in miles for a bike trip?

result_df = result_df.dropna(subset=['start_lat', 'start_lng', 'end_lat', 'end_lng'])

# Assuming 'start_lat', 'start_lng', 'end_lat', and 'end_lng' are the columns containing coordinates
result_df['start_coords'] = list(zip(result_df['start_lat'], result_df['start_lng']))
result_df['end_coords'] = list(zip(result_df['end_lat'], result_df['end_lng']))

# Calculate the distance using the Haversine formula
result_df['distance'] = result_df.apply(lambda row: geodesic(row['start_coords'], row['end_coords']).miles, axis=1)

# Calculate the average distance
average_distance = result_df['distance'].mean()

print(f"Average distance for a bike trip: {average_distance} miles")

C:\Users\mh30f\AppData\Local\Temp\ipykernel_7696\1161975977.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['start_coords'] = list(zip(result_df['start_lat'], result_df['start_lng']))
C:\Users\mh30f\AppData\Local\Temp\ipykernel_7696\1161975977.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['end_coords'] = list(zip(result_df['end_lat'], result_df['end_lng']))

Average distance for a bike trip: 1.1228549207512843 miles

C:\Users\mh30f\AppData\Local\Temp\ipykernel_7696\1161975977.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['distance'] = result_df.apply(lambda row: geodesic(row['start_coords'], row['end_coords']).miles, axis=1)

In [37]:
# Calculate the total distance traveled for each ride ID
result_df['started_at'] = pd.to_datetime(result_df['started_at'])
result_df['ended_at'] = pd.to_datetime(result_df['ended_at'])

# Calculate the trip duration in seconds
result_df['trip_duration'] = (result_df['ended_at'] - result_df['started_at']).dt.total_seconds()
total_trip_duration_per_ride = result_df.groupby('ride_id')['trip_duration'].mean()

# Sort the ride IDs based on total distance to identify the top 10
top_10_trip_duration_rides = total_trip_duration_per_ride.sort_values(ascending=False).head(10)

# Display the top 10 ride IDs with the highest distance traveled
print(top_10_trip_duration_rides)

C:\Users\mh30f\AppData\Local\Temp\ipykernel_8672\2780220241.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['started_at'] = pd.to_datetime(result_df['started_at'])
C:\Users\mh30f\AppData\Local\Temp\ipykernel_8672\2780220241.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['ended_at'] = pd.to_datetime(result_df['ended_at'])
C:\Users\mh30f\AppData\Local\Temp\ipykernel_8672\2780220241.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['trip_duration'] = (result_df['ended_at'] - result_df['started_at']).dt.total_seconds()

ride_id
13F644855866CEF3    780758.0
9F947D7B75793E0D    506344.0
9D572B15AF7EE0C8    483303.0
C4C3FE0880BC1656    408673.0
CE8E4DD7CE34BB26    402624.0
D455A259EDD83279    371655.0
CB952084776442A1    368390.0
1F73E9EFFD359084    356673.0
731C9A3E32DFB083    346820.0
AB7E57F4F792982E    346810.0
Name: trip_duration, dtype: float64

In [ ]:
# Calculate the total distance traveled for each ride ID
total_distance_per_ride = result_df.groupby('ride_id')['distance'].mean()

# Sort the ride IDs based on total distance to identify the top 10
top_10_distance_rides = total_distance_per_ride.sort_values(ascending=False).head(10)

# Display the top 10 ride IDs with the highest distance traveled
print(top_10_distance_rides)

In [ ]:
# Convert 'started_at' and 'ended_at' columns to datetime
result_df['started_at'] = pd.to_datetime(result_df['started_at'])
result_df['ended_at'] = pd.to_datetime(result_df['ended_at'])

# Calculate the trip duration in seconds
result_df['trip_duration'] = (result_df['ended_at'] - result_df['started_at']).dt.total_seconds()

# Calculate the average travel duration for each ride ID
avg_duration_per_ride = result_df.groupby('ride_id')['trip_duration'].mean()

# Sort the ride IDs based on average travel duration to identify the top 10
top_10_avg_duration_rides = avg_duration_per_ride.sort_values(ascending=False).head(10)

# Display the top 10 ride IDs with the highest average travel duration
print(top_10_avg_duration_rides)

In [ ]:
# Calculate the total number of rides for each bike
bike_counts = result_df['ride_id'].groupby(result_df['rideable_type']).count()

# Calculate the average ride duration for each bike
result_df['duration'] = (pd.to_datetime(result_df['ended_at']) - pd.to_datetime(result_df['started_at'])).dt.total_seconds()
avg_duration = result_df['duration'].groupby(result_df['rideable_type']).mean()

# Calculate the total distance traveled for each bike
# Assuming you already have a 'distance' column in your DataFrame
total_distance = result_df['distance'].groupby(result_df['rideable_type']).sum()

# Combine the metrics into a new DataFrame
bike_metrics = pd.DataFrame({
    'Total Rides': bike_counts,
    'Average Duration': avg_duration,
    'Total Distance': total_distance
})

# Calculate coefficient of variation (CV) for each metric
cv_total_rides = bike_metrics['Total Rides'].std() / bike_metrics['Total Rides'].mean()
cv_avg_duration = bike_metrics['Average Duration'].std() / bike_metrics['Average Duration'].mean()
cv_total_distance = bike_metrics['Total Distance'].std() / bike_metrics['Total Distance'].mean()

# Display the coefficients of variation
print(f'Coefficient of Variation (CV) for Total Rides: {cv_total_rides}')
print(f'Coefficient of Variation (CV) for Average Duration: {cv_avg_duration}')
print(f'Coefficient of Variation (CV) for Total Distance: {cv_total_distance}')